// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'employee_details_response.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

EmployeeDetailsResponse _$EmployeeDetailsResponseFromJson(
        Map<String, dynamic> json) =>
    EmployeeDetailsResponse(
      employeeId: json['employeeId'] as int?,
      employeeCode: json['employeeCode'] as String?,
      name: json['name'] as String?,
      rfid: json['rfid'] as String?,
      joinedDate: json['joinedDate'] as String?,
      mobileNumber: json['mobileNumber'] as String?,
      emailId: json['emailId'] as String?,
      officeName: json['officeName'] as String?,
      departmentName: json['departmentName'] as String?,
      designationName: json['designationName'] as String?,
      employeeGroupName: json['employeeGroupName'] as String?,
      levelName: json['levelName'] as String?,
      jobTypeName: json['jobTypeName'] as String?,
      workShiftName: json['workShiftName'] as String?,
      workShiftSecondName: json['workShiftSecondName'] as String?,
      profileStatus: json['profileStatus'] as String?,
      otApplicableName: json['otApplicableName'] as String?,
      userGroupName: json['userGroupName'] as String?,
      userName: json['userName'] as String?,
      status: json['status'] as int?,
      nationalityname: json['nationalityname'] as String?,
      religionName: json['religionName'] as String?,
      motherTongueName: json['motherTongueName'] as String?,
      maritalStatusName: json['maritalStatusName'] as String?,
      birthDate: json['birthDate'] as String?,
      anniversaryDate: json['anniversaryDate'] as String?,
      bloodGroupName: json['bloodGroupName'] as String?,
      height: json['height'] as String?,
      officeExtension: json['officeExtension'] as String?,
      roomNo: json['roomNo'] as String?,
      offerDate: json['offerDate'] as String?,
      confirmationDate: json['confirmationDate'] as String?,
      probationPeriodName: json['probationPeriodName'] as String?,
      gender: json['gender'] as int?,
      countryNameP: json['countryNameP'] as String?,
      stateNameP: json['stateNameP'] as String?,
      zoneNameP: json['zoneNameP'] as String?,
      districtNameP: json['districtNameP'] as String?,
      cityNameP: json['cityNameP'] as String?,
      toleP: json['toleP'] as String?,
      vdcNameP: json['vdcNameP'] as String?,
      wardNameP: json['wardNameP'] as String?,
      buildingP: json['buildingP'] as String?,
      addressP: json['addressP'] as String?,
      telephoneP: json['telephoneP'] as String?,
      poBoxP: json['poBoxP'] as String?,
      countryNameT: json['countryNameT'] as String?,
      stateNameT: json['stateNameT'] as String?,
      zoneNameT: json['zoneNameT'] as String?,
      districtNameT: json['districtNameT'] as String?,
      cityNameT: json['cityNameT'] as String?,
      toleT: json['toleT'] as String?,
      vdcNameT: json['vdcNameT'] as String?,
      wardNameT: json['wardNameT'] as String?,
      buildingT: json['buildingT'] as String?,
      addressT: json['addressT'] as String?,
      telephoneT: json['telephoneT'] as String?,
      poBoxT: json['poBoxT'] as String?,
      relationNameE: json['relationNameE'] as String?,
      nameE: json['nameE'] as String?,
      mobileE: json['mobileE'] as String?,
      emailE: json['emailE'] as String?,
    );

Map<String, dynamic> _$EmployeeDetailsResponseToJson(
        EmployeeDetailsResponse instance) =>
    <String, dynamic>{
      'employeeId': instance.employeeId,
      'employeeCode': instance.employeeCode,
      'name': instance.name,
      'rfid': instance.rfid,
      'joinedDate': instance.joinedDate,
      'mobileNumber': instance.mobileNumber,
      'emailId': instance.emailId,
      'officeName': instance.officeName,
      'departmentName': instance.departmentName,
      'designationName': instance.designationName,
      'employeeGroupName': instance.employeeGroupName,
      'levelName': instance.levelName,
      'jobTypeName': instance.jobTypeName,
      'workShiftName': instance.workShiftName,
      'workShiftSecondName': instance.workShiftSecondName,
      'profileStatus': instance.profileStatus,
      'otApplicableName': instance.otApplicableName,
      'userGroupName': instance.userGroupName,
      'userName': instance.userName,
      'status': instance.status,
      'nationalityname': instance.nationalityname,
      'religionName': instance.religionName,
      'motherTongueName': instance.motherTongueName,
      'maritalStatusName': instance.maritalStatusName,
      'birthDate': instance.birthDate,
      'anniversaryDate': instance.anniversaryDate,
      'bloodGroupName': instance.bloodGroupName,
      'height': instance.height,
      'officeExtension': instance.officeExtension,
      'roomNo': instance.roomNo,
      'offerDate': instance.offerDate,
      'confirmationDate': instance.confirmationDate,
      'probationPeriodName': instance.probationPeriodName,
      'gender': instance.gender,
      'countryNameP': instance.countryNameP,
      'stateNameP': instance.stateNameP,
      'zoneNameP': instance.zoneNameP,
      'districtNameP': instance.districtNameP,
      'cityNameP': instance.cityNameP,
      'toleP': instance.toleP,
      'vdcNameP': instance.vdcNameP,
      'wardNameP': instance.wardNameP,
      'buildingP': instance.buildingP,
      'addressP': instance.addressP,
      'telephoneP': instance.telephoneP,
      'poBoxP': instance.poBoxP,
      'countryNameT': instance.countryNameT,
      'stateNameT': instance.stateNameT,
      'zoneNameT': instance.zoneNameT,
      'districtNameT': instance.districtNameT,
      'cityNameT': instance.cityNameT,
      'toleT': instance.toleT,
      'vdcNameT': instance.vdcNameT,
      'wardNameT': instance.wardNameT,
      'buildingT': instance.buildingT,
      'addressT': instance.addressT,
      'telephoneT': instance.telephoneT,
      'poBoxT': instance.poBoxT,
      'relationNameE': instance.relationNameE,
      'nameE': instance.nameE,
      'mobileE': instance.mobileE,
      'emailE': instance.emailE,
    };
